import React, { useState } from 'react';
import { ActivityIndicator, Alert, Image, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { PurePulseTheme } from '../../theme/theme';
import { claimMobilePairCode, linkCurrentAffiliateByEmail } from '../../services/api';

export const AffiliateLinkingScreen = ({ onLinked }: { onLinked: () => Promise<void> }) => {
  const [code, setCode] = useState('');
  const [loading, setLoading] = useState(false);
  const retryEmail = async () => { setLoading(true); const linked = await linkCurrentAffiliateByEmail(); if (linked) await onLinked(); else Alert.alert('No email match', 'Sign in with the same email used by your active affiliate account, or use a pairing code from the web dashboard.'); setLoading(false); };
  const pair = async () => { if (!code.trim()) return; setLoading(true); const result = await claimMobilePairCode(code); if (result.success) await onLinked(); else Alert.alert('Linking failed', result.error || 'The pairing code is invalid or expired.'); setLoading(false); };
  return <View style={styles.root}><View style={styles.card}><Image source={require('../../../assets/icon.png')} style={styles.logo} /><Text style={styles.title}>Link your affiliate account</Text><Text style={styles.body}>First, we securely look for an active PurePulse affiliate with the exact email you used to sign in.</Text><TouchableOpacity style={styles.primary} onPress={retryEmail} disabled={loading}>{loading ? <ActivityIndicator color="#fff" /> : <Text style={styles.primaryText}>Link using my email</Text>}</TouchableOpacity><View style={styles.divider}><View style={styles.line} /><Text style={styles.or}>OR</Text><View style={styles.line} /></View><Text style={styles.body}>In PurePulseAdmin, open your affiliate dashboard and generate a mobile pairing code.</Text><TextInput style={styles.input} value={code} onChangeText={setCode} autoCapitalize="characters" autoCorrect={false} placeholder="PX-4892" placeholderTextColor={PurePulseTheme.colors.textMuted} maxLength={10} /><TouchableOpacity style={styles.secondary} onPress={pair} disabled={loading}><Text style={styles.secondaryText}>Link with pairing code</Text></TouchableOpacity><Text style={styles.note}>A code can only link the affiliate account it was generated for and expires automatically.</Text></View></View>;
};

const styles = StyleSheet.create({ root: { flex: 1, padding: 20, justifyContent: 'center', backgroundColor: PurePulseTheme.colors.background }, card: { padding: 22, borderRadius: 18, borderWidth: 1, borderColor: PurePulseTheme.colors.cardBorderActive, backgroundColor: PurePulseTheme.colors.cardBg }, logo: { width: 58, height: 58, borderRadius: 14, alignSelf: 'center', marginBottom: 14 }, title: { color: PurePulseTheme.colors.textPrimary, fontSize: 21, fontWeight: '900', textAlign: 'center' }, body: { color: PurePulseTheme.colors.textSecondary, fontSize: 13, lineHeight: 19, textAlign: 'center', marginTop: 9 }, primary: { minHeight: 46, marginTop: 18, alignItems: 'center', justifyContent: 'center', borderRadius: 11, backgroundColor: PurePulseTheme.colors.primary }, primaryText: { color: '#fff', fontWeight: '800' }, divider: { flexDirection: 'row', alignItems: 'center', gap: 10, marginVertical: 17 }, line: { flex: 1, height: 1, backgroundColor: PurePulseTheme.colors.cardBorder }, or: { color: PurePulseTheme.colors.textMuted, fontSize: 10, fontWeight: '800' }, input: { color: '#fff', fontSize: 18, fontWeight: '900', letterSpacing: 2, textAlign: 'center', marginTop: 13, padding: 11, borderRadius: 10, borderWidth: 1, borderColor: PurePulseTheme.colors.primaryLight, backgroundColor: PurePulseTheme.colors.cardBgSecondary }, secondary: { minHeight: 44, marginTop: 10, alignItems: 'center', justifyContent: 'center', borderRadius: 11, borderWidth: 1, borderColor: PurePulseTheme.colors.primaryLight }, secondaryText: { color: PurePulseTheme.colors.primaryLight, fontWeight: '800' }, note: { color: PurePulseTheme.colors.textMuted, fontSize: 10, lineHeight: 15, textAlign: 'center', marginTop: 12 } });
